model: dataflux-ispy

framework: pytorch

workflow:
  generate_data: False
  train: True
  checkpoint: False

dataset:
  gcp_project_name: gcs-tess
  gcs_bucket: dataflux-tessellations-datasets
  data_folder: ispy-dlio
  format: dcm
  num_files_train: 7005030
  num_samples_per_file: 1

reader:
  data_loader: dataflux_pytorch
  batch_size: 1024
  read_threads: 4
  file_shuffle: seed
  sample_shuffle: seed

train:
  epochs: 5
  computation_time: 1.3604

checkpoint:
  checkpoint_folder: checkpoints/yaml
  checkpoint_after_epoch: 5
  epochs_between_checkpoints: 2
  model_size: 499153191
