model: dataflux

framework: pytorch

workflow:
  generate_data: False
  train: True
  checkpoint: False

dataset:
  gcp_project_name: gcs-tess
  gcs_bucket: dataflux-tessellations-datasets
  data_folder: UNet3D/micro/100KB-50GB
  format: npz
  num_files_train: 50000
  num_samples_per_file: 1
  record_length: 100000
  record_length_stdev: 0
  record_length_resize: 0

reader:
  data_loader: dataflux_pytorch
  batch_size: 4
  read_threads: 4
  file_shuffle: seed
  sample_shuffle: seed

train:
  epochs: 5
  computation_time: 1.3604
